# Generated by Django 6.1.1 on 2026-09-17 16:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='sources/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DOWNLOADING', 'Downloading Video'), ('EXTRACTING_AUDIO', 'Extracting Audio'), ('TRANSCRIBING', 'Transcribing Audio'), ('ANALYZING_HOOK', 'Finding Viral Hook'), ('CUTTING_VIDEO', 'Rendering 9:16 Clip'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=30)),
                ('progress', models.IntegerField(default=0)),
                ('hook_start', models.FloatField(blank=True, null=True)),
                ('hook_end', models.FloatField(blank=True, null=True)),
                ('hook_title', models.CharField(blank=True, max_length=255)),
                ('hook_reasoning', models.TextField(blank=True)),
                ('output_video', models.FileField(blank=True, null=True, upload_to='hooks/')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
